// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: assets.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const archiveAsset = `-- name: ArchiveAsset :execrows
UPDATE assets
SET archived_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = ? AND archived_at IS NULL
`

// Soft-delete. Returns RowsAffected so the caller can distinguish:
//
//	rows=0  +  asset exists      -> already archived (idempotent no-op)
//	rows=0  +  asset missing     -> 404
//	rows=1                       -> archived just now
//
// The "exists?" check stays in store.go because sqlc :execrows can't combine
// two statements.
func (q *Queries) ArchiveAsset(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveAsset, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const assetExistsByID = `-- name: AssetExistsByID :one
SELECT COUNT(*) FROM assets WHERE id = ?
`

// Used by ArchiveAsset's "already-archived vs not-found" disambiguation.
func (q *Queries) AssetExistsByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, assetExistsByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAssetByCode = `-- name: GetAssetByCode :one
SELECT id, code, name, asset_type, bucket, channel, currency, risk_level, holding_cost_pct, expected_yield_pct, notes, created_at, archived_at FROM assets
WHERE code = ?
`

func (q *Queries) GetAssetByCode(ctx context.Context, code string) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAssetByCode, code)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AssetType,
		&i.Bucket,
		&i.Channel,
		&i.Currency,
		&i.RiskLevel,
		&i.HoldingCostPct,
		&i.ExpectedYieldPct,
		&i.Notes,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, code, name, asset_type, bucket, channel, currency, risk_level, holding_cost_pct, expected_yield_pct, notes, created_at, archived_at FROM assets
WHERE id = ? AND archived_at IS NULL
`

// Excludes archived rows on purpose: the HTTP layer treats an archived asset
// as "not found" for read paths so the UI doesn't have to filter.
func (q *Queries) GetAssetByID(ctx context.Context, id int64) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AssetType,
		&i.Bucket,
		&i.Channel,
		&i.Currency,
		&i.RiskLevel,
		&i.HoldingCostPct,
		&i.ExpectedYieldPct,
		&i.Notes,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getAssetIDByCode = `-- name: GetAssetIDByCode :one
SELECT id FROM assets WHERE code = ?
`

func (q *Queries) GetAssetIDByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAssetIDByCode, code)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, code, name, asset_type, bucket, channel, currency, risk_level, holding_cost_pct, expected_yield_pct, notes, created_at, archived_at FROM assets
WHERE archived_at IS NULL
ORDER BY bucket, asset_type, code
`

// All non-archived assets, ordered for stable CSV publish.
// Note: filtered variants (bucket / asset_type / include_archived) live in
// internal/db/store/store.go (ListAssetsFiltered) because sqlc cannot generate
// the optional WHERE conditions.
func (q *Queries) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.AssetType,
			&i.Bucket,
			&i.Channel,
			&i.Currency,
			&i.RiskLevel,
			&i.HoldingCostPct,
			&i.ExpectedYieldPct,
			&i.Notes,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAssetByCode = `-- name: UpsertAssetByCode :one
INSERT INTO assets (
  code, name, asset_type, bucket, channel, currency,
  risk_level, holding_cost_pct, expected_yield_pct, notes
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (code) DO UPDATE SET
  name               = excluded.name,
  asset_type         = excluded.asset_type,
  bucket             = excluded.bucket,
  channel            = excluded.channel,
  currency           = excluded.currency,
  risk_level         = excluded.risk_level,
  holding_cost_pct   = excluded.holding_cost_pct,
  expected_yield_pct = excluded.expected_yield_pct,
  notes              = excluded.notes,
  archived_at        = NULL
RETURNING id
`

type UpsertAssetByCodeParams struct {
	Code             string          `json:"code"`
	Name             string          `json:"name"`
	AssetType        string          `json:"asset_type"`
	Bucket           string          `json:"bucket"`
	Channel          string          `json:"channel"`
	Currency         string          `json:"currency"`
	RiskLevel        sql.NullString  `json:"risk_level"`
	HoldingCostPct   sql.NullFloat64 `json:"holding_cost_pct"`
	ExpectedYieldPct sql.NullFloat64 `json:"expected_yield_pct"`
	Notes            string          `json:"notes"`
}

// M1.5 contract:
//   - Idempotent on `code` (natural key)
//   - Re-creating an already-archived asset clears archived_at ("revive")
//   - Returns the row id (LastInsertId is unreliable for ON CONFLICT paths)
func (q *Queries) UpsertAssetByCode(ctx context.Context, arg UpsertAssetByCodeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertAssetByCode,
		arg.Code,
		arg.Name,
		arg.AssetType,
		arg.Bucket,
		arg.Channel,
		arg.Currency,
		arg.RiskLevel,
		arg.HoldingCostPct,
		arg.ExpectedYieldPct,
		arg.Notes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
