// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: bucket_targets.sql

package sqlcgen

import (
	"context"
)

const deleteBucketTarget = `-- name: DeleteBucketTarget :execrows
DELETE FROM bucket_targets WHERE bucket = ?
`

func (q *Queries) DeleteBucketTarget(ctx context.Context, bucket string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBucketTarget, bucket)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBucketTarget = `-- name: GetBucketTarget :one
SELECT bucket, target_pct, notes, updated_at FROM bucket_targets WHERE bucket = ?
`

func (q *Queries) GetBucketTarget(ctx context.Context, bucket string) (BucketTarget, error) {
	row := q.db.QueryRowContext(ctx, getBucketTarget, bucket)
	var i BucketTarget
	err := row.Scan(
		&i.Bucket,
		&i.TargetPct,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}

const listBucketTargets = `-- name: ListBucketTargets :many
SELECT bucket, target_pct, notes, updated_at FROM bucket_targets
ORDER BY
  CASE bucket
    WHEN 'cash'   THEN 1
    WHEN 'stable' THEN 2
    WHEN 'growth' THEN 3
  END
`

// All target rows; we always return all 3 buckets even if some have no row
// (handler layer fills missing buckets with target_pct=null in the response).
func (q *Queries) ListBucketTargets(ctx context.Context) ([]BucketTarget, error) {
	rows, err := q.db.QueryContext(ctx, listBucketTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BucketTarget
	for rows.Next() {
		var i BucketTarget
		if err := rows.Scan(
			&i.Bucket,
			&i.TargetPct,
			&i.Notes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBucketTarget = `-- name: UpsertBucketTarget :one
INSERT INTO bucket_targets (bucket, target_pct, notes)
VALUES (?, ?, ?)
ON CONFLICT (bucket) DO UPDATE SET
  target_pct = excluded.target_pct,
  notes      = excluded.notes,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
RETURNING bucket, target_pct, notes, updated_at
`

type UpsertBucketTargetParams struct {
	Bucket    string  `json:"bucket"`
	TargetPct float64 `json:"target_pct"`
	Notes     string  `json:"notes"`
}

// Idempotent on `bucket`. Always bumps updated_at on overwrite so the audit
// trail / CSV export shows the last edit time.
func (q *Queries) UpsertBucketTarget(ctx context.Context, arg UpsertBucketTargetParams) (BucketTarget, error) {
	row := q.db.QueryRowContext(ctx, upsertBucketTarget, arg.Bucket, arg.TargetPct, arg.Notes)
	var i BucketTarget
	err := row.Scan(
		&i.Bucket,
		&i.TargetPct,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}
