// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: holdings.sql

package sqlcgen

import (
	"context"
)

const listHoldings = `-- name: ListHoldings :many
SELECT
  asset_id,
  asset_code,
  asset_name,
  asset_type,
  bucket,
  channel,
  currency,
  risk_level,
  as_of,
  balance_cents,
  expected_yield_pct
FROM holdings
ORDER BY bucket, asset_type, asset_code
`

func (q *Queries) ListHoldings(ctx context.Context) ([]Holding, error) {
	rows, err := q.db.QueryContext(ctx, listHoldings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Holding
	for rows.Next() {
		var i Holding
		if err := rows.Scan(
			&i.AssetID,
			&i.AssetCode,
			&i.AssetName,
			&i.AssetType,
			&i.Bucket,
			&i.Channel,
			&i.Currency,
			&i.RiskLevel,
			&i.AsOf,
			&i.BalanceCents,
			&i.ExpectedYieldPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
