// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlcgen

import (
	"database/sql"
)

type Asset struct {
	ID               int64           `json:"id"`
	Code             string          `json:"code"`
	Name             string          `json:"name"`
	AssetType        string          `json:"asset_type"`
	Bucket           string          `json:"bucket"`
	Channel          string          `json:"channel"`
	Currency         string          `json:"currency"`
	RiskLevel        sql.NullString  `json:"risk_level"`
	HoldingCostPct   sql.NullFloat64 `json:"holding_cost_pct"`
	ExpectedYieldPct sql.NullFloat64 `json:"expected_yield_pct"`
	Notes            string          `json:"notes"`
	CreatedAt        string          `json:"created_at"`
	ArchivedAt       sql.NullString  `json:"archived_at"`
}

type Holding struct {
	AssetID          int64    `json:"asset_id"`
	AssetCode        string   `json:"asset_code"`
	AssetName        string   `json:"asset_name"`
	AssetType        string   `json:"asset_type"`
	Bucket           string   `json:"bucket"`
	Channel          string   `json:"channel"`
	Currency         string   `json:"currency"`
	RiskLevel        *string  `json:"risk_level"`
	AsOf             *string  `json:"as_of"`
	BalanceCents     *int64   `json:"balance_cents"`
	ExpectedYieldPct *float64 `json:"expected_yield_pct"`
}

type Snapshot struct {
	ID               int64           `json:"id"`
	AssetID          int64           `json:"asset_id"`
	SnapshotDate     string          `json:"snapshot_date"`
	BalanceCents     int64           `json:"balance_cents"`
	ExpectedYieldPct sql.NullFloat64 `json:"expected_yield_pct"`
	ActualYieldPct   sql.NullFloat64 `json:"actual_yield_pct"`
	Notes            string          `json:"notes"`
	CreatedAt        string          `json:"created_at"`
}

type Transaction struct {
	ID          int64  `json:"id"`
	AssetID     int64  `json:"asset_id"`
	TxnDate     string `json:"txn_date"`
	Direction   string `json:"direction"`
	AmountCents int64  `json:"amount_cents"`
	FeeCents    int64  `json:"fee_cents"`
	Notes       string `json:"notes"`
	CreatedAt   string `json:"created_at"`
}
