// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	// Soft-delete. Returns RowsAffected so the caller can distinguish:
	//   rows=0  +  asset exists      -> already archived (idempotent no-op)
	//   rows=0  +  asset missing     -> 404
	//   rows=1                       -> archived just now
	// The "exists?" check stays in store.go because sqlc :execrows can't combine
	// two statements.
	ArchiveAsset(ctx context.Context, id int64) (int64, error)
	// Used by ArchiveAsset's "already-archived vs not-found" disambiguation.
	AssetExistsByID(ctx context.Context, id int64) (int64, error)
	DeleteBucketTarget(ctx context.Context, bucket string) (int64, error)
	// Hard delete (no soft-delete on snapshots, they're cheap to recreate).
	DeleteSnapshot(ctx context.Context, id int64) (int64, error)
	DeleteTransaction(ctx context.Context, id int64) (int64, error)
	GetAssetByCode(ctx context.Context, code string) (Asset, error)
	// Excludes archived rows on purpose: the HTTP layer treats an archived asset
	// as "not found" for read paths so the UI doesn't have to filter.
	GetAssetByID(ctx context.Context, id int64) (Asset, error)
	GetAssetIDByCode(ctx context.Context, code string) (int64, error)
	GetBucketTarget(ctx context.Context, bucket string) (BucketTarget, error)
	GetSnapshotByID(ctx context.Context, id int64) (GetSnapshotByIDRow, error)
	GetTransactionByID(ctx context.Context, id int64) (GetTransactionByIDRow, error)
	// Append-only. Transactions have no natural unique key (an asset can buy
	// twice the same day at the same price), so duplicate-prevention is the
	// caller's responsibility.
	// Returns the new row id via RETURNING for ergonomic post-insert read-back.
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error)
	// All non-archived assets, ordered for stable CSV publish.
	// Note: filtered variants (bucket / asset_type / include_archived) live in
	// internal/db/store/store.go (ListAssetsFiltered) because sqlc cannot generate
	// the optional WHERE conditions.
	ListAssets(ctx context.Context) ([]Asset, error)
	// All target rows; we always return all 3 buckets even if some have no row
	// (handler layer fills missing buckets with target_pct=null in the response).
	ListBucketTargets(ctx context.Context) ([]BucketTarget, error)
	ListHoldings(ctx context.Context) ([]Holding, error)
	// All snapshots, joined with assets for code/name display columns. Used by
	// both the GET API and the publish job's snapshots-*.csv dump.
	// Filtered variants (asset_id / since / until) live in store.ListSnapshotsFiltered.
	ListSnapshots(ctx context.Context) ([]ListSnapshotsRow, error)
	// All transactions, joined with assets for code/name display columns.
	// Filtered variants (asset_id / direction / since / until) live in
	// store.ListTransactionsFiltered.
	ListTransactions(ctx context.Context) ([]ListTransactionsRow, error)
	// M1.5 contract:
	//   - Idempotent on `code` (natural key)
	//   - Re-creating an already-archived asset clears archived_at ("revive")
	//   - Returns the row id (LastInsertId is unreliable for ON CONFLICT paths)
	UpsertAssetByCode(ctx context.Context, arg UpsertAssetByCodeParams) (int64, error)
	// Idempotent on `bucket`. Always bumps updated_at on overwrite so the audit
	// trail / CSV export shows the last edit time.
	UpsertBucketTarget(ctx context.Context, arg UpsertBucketTargetParams) (BucketTarget, error)
	// Idempotent on (asset_id, snapshot_date). Returns row id so the caller can
	// 200 + read-back without a separate SELECT.
	UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
