// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: snapshots.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteSnapshot = `-- name: DeleteSnapshot :execrows
DELETE FROM snapshots WHERE id = ?
`

// Hard delete (no soft-delete on snapshots, they're cheap to recreate).
func (q *Queries) DeleteSnapshot(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSnapshot, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSnapshotByID = `-- name: GetSnapshotByID :one
SELECT
  s.id,
  s.asset_id,
  a.code              AS asset_code,
  a.name              AS asset_name,
  s.snapshot_date,
  s.balance_cents,
  s.expected_yield_pct,
  s.actual_yield_pct,
  s.notes,
  s.created_at
FROM snapshots s
JOIN assets a ON a.id = s.asset_id
WHERE s.id = ?
`

type GetSnapshotByIDRow struct {
	ID               int64           `json:"id"`
	AssetID          int64           `json:"asset_id"`
	AssetCode        string          `json:"asset_code"`
	AssetName        string          `json:"asset_name"`
	SnapshotDate     string          `json:"snapshot_date"`
	BalanceCents     int64           `json:"balance_cents"`
	ExpectedYieldPct sql.NullFloat64 `json:"expected_yield_pct"`
	ActualYieldPct   sql.NullFloat64 `json:"actual_yield_pct"`
	Notes            string          `json:"notes"`
	CreatedAt        string          `json:"created_at"`
}

func (q *Queries) GetSnapshotByID(ctx context.Context, id int64) (GetSnapshotByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotByID, id)
	var i GetSnapshotByIDRow
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.AssetCode,
		&i.AssetName,
		&i.SnapshotDate,
		&i.BalanceCents,
		&i.ExpectedYieldPct,
		&i.ActualYieldPct,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT
  s.id,
  s.asset_id,
  a.code              AS asset_code,
  a.name              AS asset_name,
  s.snapshot_date,
  s.balance_cents,
  s.expected_yield_pct,
  s.actual_yield_pct,
  s.notes,
  s.created_at
FROM snapshots s
JOIN assets a ON a.id = s.asset_id
ORDER BY s.snapshot_date DESC, a.code
`

type ListSnapshotsRow struct {
	ID               int64           `json:"id"`
	AssetID          int64           `json:"asset_id"`
	AssetCode        string          `json:"asset_code"`
	AssetName        string          `json:"asset_name"`
	SnapshotDate     string          `json:"snapshot_date"`
	BalanceCents     int64           `json:"balance_cents"`
	ExpectedYieldPct sql.NullFloat64 `json:"expected_yield_pct"`
	ActualYieldPct   sql.NullFloat64 `json:"actual_yield_pct"`
	Notes            string          `json:"notes"`
	CreatedAt        string          `json:"created_at"`
}

// All snapshots, joined with assets for code/name display columns. Used by
// both the GET API and the publish job's snapshots-*.csv dump.
// Filtered variants (asset_id / since / until) live in store.ListSnapshotsFiltered.
func (q *Queries) ListSnapshots(ctx context.Context) ([]ListSnapshotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSnapshotsRow
	for rows.Next() {
		var i ListSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.AssetCode,
			&i.AssetName,
			&i.SnapshotDate,
			&i.BalanceCents,
			&i.ExpectedYieldPct,
			&i.ActualYieldPct,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSnapshot = `-- name: UpsertSnapshot :one
INSERT INTO snapshots (
  asset_id, snapshot_date, balance_cents, expected_yield_pct, actual_yield_pct, notes
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (asset_id, snapshot_date) DO UPDATE SET
  balance_cents      = excluded.balance_cents,
  expected_yield_pct = excluded.expected_yield_pct,
  actual_yield_pct   = excluded.actual_yield_pct,
  notes              = excluded.notes
RETURNING id
`

type UpsertSnapshotParams struct {
	AssetID          int64           `json:"asset_id"`
	SnapshotDate     string          `json:"snapshot_date"`
	BalanceCents     int64           `json:"balance_cents"`
	ExpectedYieldPct sql.NullFloat64 `json:"expected_yield_pct"`
	ActualYieldPct   sql.NullFloat64 `json:"actual_yield_pct"`
	Notes            string          `json:"notes"`
}

// Idempotent on (asset_id, snapshot_date). Returns row id so the caller can
// 200 + read-back without a separate SELECT.
func (q *Queries) UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertSnapshot,
		arg.AssetID,
		arg.SnapshotDate,
		arg.BalanceCents,
		arg.ExpectedYieldPct,
		arg.ActualYieldPct,
		arg.Notes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
