// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: transactions.sql

package sqlcgen

import (
	"context"
)

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT
  t.id,
  t.asset_id,
  a.code            AS asset_code,
  a.name            AS asset_name,
  t.txn_date,
  t.direction,
  t.amount_cents,
  t.fee_cents,
  t.notes,
  t.created_at
FROM transactions t
JOIN assets a ON a.id = t.asset_id
WHERE t.id = ?
`

type GetTransactionByIDRow struct {
	ID          int64  `json:"id"`
	AssetID     int64  `json:"asset_id"`
	AssetCode   string `json:"asset_code"`
	AssetName   string `json:"asset_name"`
	TxnDate     string `json:"txn_date"`
	Direction   string `json:"direction"`
	AmountCents int64  `json:"amount_cents"`
	FeeCents    int64  `json:"fee_cents"`
	Notes       string `json:"notes"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, id int64) (GetTransactionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.AssetCode,
		&i.AssetName,
		&i.TxnDate,
		&i.Direction,
		&i.AmountCents,
		&i.FeeCents,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
  asset_id, txn_date, direction, amount_cents, fee_cents, notes
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertTransactionParams struct {
	AssetID     int64  `json:"asset_id"`
	TxnDate     string `json:"txn_date"`
	Direction   string `json:"direction"`
	AmountCents int64  `json:"amount_cents"`
	FeeCents    int64  `json:"fee_cents"`
	Notes       string `json:"notes"`
}

// Append-only. Transactions have no natural unique key (an asset can buy
// twice the same day at the same price), so duplicate-prevention is the
// caller's responsibility.
// Returns the new row id via RETURNING for ergonomic post-insert read-back.
func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTransaction,
		arg.AssetID,
		arg.TxnDate,
		arg.Direction,
		arg.AmountCents,
		arg.FeeCents,
		arg.Notes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
  t.id,
  t.asset_id,
  a.code            AS asset_code,
  a.name            AS asset_name,
  t.txn_date,
  t.direction,
  t.amount_cents,
  t.fee_cents,
  t.notes,
  t.created_at
FROM transactions t
JOIN assets a ON a.id = t.asset_id
ORDER BY t.txn_date DESC, t.id DESC
`

type ListTransactionsRow struct {
	ID          int64  `json:"id"`
	AssetID     int64  `json:"asset_id"`
	AssetCode   string `json:"asset_code"`
	AssetName   string `json:"asset_name"`
	TxnDate     string `json:"txn_date"`
	Direction   string `json:"direction"`
	AmountCents int64  `json:"amount_cents"`
	FeeCents    int64  `json:"fee_cents"`
	Notes       string `json:"notes"`
	CreatedAt   string `json:"created_at"`
}

// All transactions, joined with assets for code/name display columns.
// Filtered variants (asset_id / direction / since / until) live in
// store.ListTransactionsFiltered.
func (q *Queries) ListTransactions(ctx context.Context) ([]ListTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.AssetCode,
			&i.AssetName,
			&i.TxnDate,
			&i.Direction,
			&i.AmountCents,
			&i.FeeCents,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
