// Package store wraps the SQL queries needed by the finance backend.
//
// M1.6 architecture (hybrid sqlc + hand-rolled):
//
//   Static SQL (compile-time-checked, type-generated by sqlc) lives in
//   internal/db/queries/*.sql -> internal/db/sqlc/. This store package
//   delegates each fixed-shape query to sqlcgen.Queries and converts the
//   generated types into the store's public Asset/Snapshot/... structs so
//   downstream code (handler/dto, csvexport, publish, cmd/seed, cmd/import)
//   doesn't have to know sqlc exists.
//
//   Dynamic SQL (cannot be generated):
//     - List*Filtered (optional WHERE clauses, 0..N predicates)
//     - Patch* (optional SET clauses, 0..N fields)
//   These remain hand-rolled in this file. They build SQL with strings.Join
//   on []string fragments + []any args. Drift risk: if you add a column to
//   assets, both the migration AND the patch builder need updating; sqlc
//   does NOT catch that here.
//
// Why hybrid and not "sqlc everything":
//   sqlc has no native dynamic-SQL story (sqlc.narg / sqlc.arg covers
//   nullable params but not "skip this WHERE clause entirely"). Workarounds
//   like "SELECT ... WHERE (? IS NULL OR col = ?)" produce table-scan plans
//   on filtered queries. Hand-rolled dynamic SQL is faster and clearer for
//   the few cases that need it.
//
// Why not "sqlc nothing":
//   When M1 and M1.5 hand-rolled all SQL, a column rename in 0001 migration
//   would only break at runtime via "no such column: X". With sqlc the same
//   change breaks `sqlc generate` immediately and the build fails. That's
//   the main value-add — schema/query co-evolution checked at build time.
package store

import (
	"context"
	"database/sql"
	"strings"

	sqlcgen "github.com/walker-qiang/personal-finance/internal/db/sqlc"
)

type Store struct {
	db *sql.DB
	q  *sqlcgen.Queries // sqlc handle for static-SQL paths
}

func New(db *sql.DB) *Store {
	return &Store{db: db, q: sqlcgen.New(db)}
}

// --- Asset ---

// Asset is the store's public type. We deliberately omit ArchivedAt (which
// sqlcgen.Asset has) because every read path either filters out archived
// rows (default) or is the dedicated ArchiveAsset write path — no caller
// needs to read archived_at directly.
type Asset struct {
	ID               int64
	Code             string
	Name             string
	AssetType        string
	Bucket           string
	Channel          string
	Currency         string
	RiskLevel        sql.NullString
	HoldingCostPct   sql.NullFloat64
	ExpectedYieldPct sql.NullFloat64
	Notes            string
	CreatedAt        string
}

func assetFromSQLC(a sqlcgen.Asset) Asset {
	return Asset{
		ID:               a.ID,
		Code:             a.Code,
		Name:             a.Name,
		AssetType:        a.AssetType,
		Bucket:           a.Bucket,
		Channel:          a.Channel,
		Currency:         a.Currency,
		RiskLevel:        a.RiskLevel,
		HoldingCostPct:   a.HoldingCostPct,
		ExpectedYieldPct: a.ExpectedYieldPct,
		Notes:            a.Notes,
		CreatedAt:        a.CreatedAt,
	}
}

// UpsertAsset inserts or overwrites the asset identified by code. Returns
// the row id (existing on update, new on insert).
//
// Note: this also revives soft-deleted (archived) rows by clearing
// archived_at. Re-creating an asset with the same code therefore "undeletes"
// it, which is what we want for personal use (a typo'd ARCHIVE → POST again).
func (s *Store) UpsertAsset(ctx context.Context, a Asset) (int64, error) {
	return s.q.UpsertAssetByCode(ctx, sqlcgen.UpsertAssetByCodeParams{
		Code:             a.Code,
		Name:             a.Name,
		AssetType:        a.AssetType,
		Bucket:           a.Bucket,
		Channel:          a.Channel,
		Currency:         a.Currency,
		RiskLevel:        a.RiskLevel,
		HoldingCostPct:   a.HoldingCostPct,
		ExpectedYieldPct: a.ExpectedYieldPct,
		Notes:            a.Notes,
	})
}

// AssetFilter narrows ListAssetsFiltered. Zero value = "all non-archived".
type AssetFilter struct {
	Bucket          string // "", "cash", "stable", "growth"
	AssetType       string // "" or one of the 8 enums
	IncludeArchived bool
}

// ListAssets is the unfiltered fast path; delegates to sqlc.
func (s *Store) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := s.q.ListAssets(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]Asset, len(rows))
	for i, r := range rows {
		out[i] = assetFromSQLC(r)
	}
	return out, nil
}

// ListAssetsFiltered builds dynamic SQL because sqlc can't express "skip this
// WHERE clause if the field is empty" without a full table scan.
func (s *Store) ListAssetsFiltered(ctx context.Context, f AssetFilter) ([]Asset, error) {
	// Fast path: zero filter == ListAssets, use sqlc.
	if !f.IncludeArchived && f.Bucket == "" && f.AssetType == "" {
		return s.ListAssets(ctx)
	}
	where := []string{}
	args := []any{}
	if !f.IncludeArchived {
		where = append(where, "archived_at IS NULL")
	}
	if f.Bucket != "" {
		where = append(where, "bucket = ?")
		args = append(args, f.Bucket)
	}
	if f.AssetType != "" {
		where = append(where, "asset_type = ?")
		args = append(args, f.AssetType)
	}
	q := `SELECT id, code, name, asset_type, bucket, channel, currency,
       risk_level, holding_cost_pct, expected_yield_pct, notes, created_at
FROM assets`
	if len(where) > 0 {
		q += " WHERE " + strings.Join(where, " AND ")
	}
	q += " ORDER BY bucket, asset_type, code"
	rows, err := s.db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Asset
	for rows.Next() {
		var a Asset
		if err := rows.Scan(
			&a.ID, &a.Code, &a.Name, &a.AssetType, &a.Bucket, &a.Channel, &a.Currency,
			&a.RiskLevel, &a.HoldingCostPct, &a.ExpectedYieldPct, &a.Notes, &a.CreatedAt,
		); err != nil {
			return nil, err
		}
		out = append(out, a)
	}
	return out, rows.Err()
}

func (s *Store) GetAssetIDByCode(ctx context.Context, code string) (int64, error) {
	return s.q.GetAssetIDByCode(ctx, code)
}

func (s *Store) GetAssetByID(ctx context.Context, id int64) (Asset, error) {
	a, err := s.q.GetAssetByID(ctx, id)
	if err != nil {
		return Asset{}, err
	}
	return assetFromSQLC(a), nil
}

// AssetPatch holds partial-update fields. nil = leave alone.
type AssetPatch struct {
	Name             *string
	AssetType        *string
	Bucket           *string
	Channel          *string
	Currency         *string
	RiskLevel        *string // pass empty string to clear
	HoldingCostPct   *float64
	ClearHoldingCost bool // pass true to set NULL
	ExpectedYieldPct *float64
	ClearExpectedY   bool
	Notes            *string
}

// PatchAsset updates only the provided fields. Returns sql.ErrNoRows if id
// does not exist or is archived.
//
// Hand-rolled because sqlc can't generate "build SET clause from N optional
// fields". A column added to assets must be added here too — drift risk.
func (s *Store) PatchAsset(ctx context.Context, id int64, p AssetPatch) error {
	sets := []string{}
	args := []any{}
	if p.Name != nil {
		sets = append(sets, "name = ?")
		args = append(args, *p.Name)
	}
	if p.AssetType != nil {
		sets = append(sets, "asset_type = ?")
		args = append(args, *p.AssetType)
	}
	if p.Bucket != nil {
		sets = append(sets, "bucket = ?")
		args = append(args, *p.Bucket)
	}
	if p.Channel != nil {
		sets = append(sets, "channel = ?")
		args = append(args, *p.Channel)
	}
	if p.Currency != nil {
		sets = append(sets, "currency = ?")
		args = append(args, *p.Currency)
	}
	if p.RiskLevel != nil {
		if *p.RiskLevel == "" {
			sets = append(sets, "risk_level = NULL")
		} else {
			sets = append(sets, "risk_level = ?")
			args = append(args, *p.RiskLevel)
		}
	}
	if p.ClearHoldingCost {
		sets = append(sets, "holding_cost_pct = NULL")
	} else if p.HoldingCostPct != nil {
		sets = append(sets, "holding_cost_pct = ?")
		args = append(args, *p.HoldingCostPct)
	}
	if p.ClearExpectedY {
		sets = append(sets, "expected_yield_pct = NULL")
	} else if p.ExpectedYieldPct != nil {
		sets = append(sets, "expected_yield_pct = ?")
		args = append(args, *p.ExpectedYieldPct)
	}
	if p.Notes != nil {
		sets = append(sets, "notes = ?")
		args = append(args, *p.Notes)
	}
	if len(sets) == 0 {
		// no-op patch is allowed; verify the row exists so the handler can
		// return 404 vs 200 correctly. We can use sqlc's GetAssetByID for
		// the existence check (it already filters archived).
		if _, err := s.q.GetAssetByID(ctx, id); err != nil {
			return err
		}
		return nil
	}
	args = append(args, id)
	q := "UPDATE assets SET " + strings.Join(sets, ", ") + " WHERE id = ? AND archived_at IS NULL"
	res, err := s.db.ExecContext(ctx, q, args...)
	if err != nil {
		return err
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return sql.ErrNoRows
	}
	return nil
}

// ArchiveAsset soft-deletes (sets archived_at = now). Idempotent: archiving
// an already-archived row is a no-op (returns nil, not ErrNoRows).
//
// Two-statement disambiguation lives here because sqlc :execrows can't fold
// "did the UPDATE hit + does the row exist" into one call.
func (s *Store) ArchiveAsset(ctx context.Context, id int64) error {
	rows, err := s.q.ArchiveAsset(ctx, id)
	if err != nil {
		return err
	}
	if rows == 0 {
		exists, err := s.q.AssetExistsByID(ctx, id)
		if err != nil {
			return err
		}
		if exists == 0 {
			return sql.ErrNoRows
		}
		// Row exists but already archived; treat as success (idempotent).
	}
	return nil
}

// --- Snapshot ---

type Snapshot struct {
	ID               int64
	AssetID          int64
	AssetCode        string
	AssetName        string
	SnapshotDate     string
	BalanceCents     int64
	ExpectedYieldPct sql.NullFloat64
	ActualYieldPct   sql.NullFloat64
	Notes            string
	CreatedAt        string
}

// snapshotFromListRow / FromGetRow: sqlc generates a per-query Row struct
// when the SELECT projects custom column names (here: asset_code from a JOIN).
// The two row structs are field-identical, so we have two adapters — annoying
// but deterministic. If sqlc ever supports "use this user struct as the
// return type", we collapse them.
func snapshotFromListRow(r sqlcgen.ListSnapshotsRow) Snapshot {
	return Snapshot{
		ID:               r.ID,
		AssetID:          r.AssetID,
		AssetCode:        r.AssetCode,
		AssetName:        r.AssetName,
		SnapshotDate:     r.SnapshotDate,
		BalanceCents:     r.BalanceCents,
		ExpectedYieldPct: r.ExpectedYieldPct,
		ActualYieldPct:   r.ActualYieldPct,
		Notes:            r.Notes,
		CreatedAt:        r.CreatedAt,
	}
}

func snapshotFromGetRow(r sqlcgen.GetSnapshotByIDRow) Snapshot {
	return Snapshot{
		ID:               r.ID,
		AssetID:          r.AssetID,
		AssetCode:        r.AssetCode,
		AssetName:        r.AssetName,
		SnapshotDate:     r.SnapshotDate,
		BalanceCents:     r.BalanceCents,
		ExpectedYieldPct: r.ExpectedYieldPct,
		ActualYieldPct:   r.ActualYieldPct,
		Notes:            r.Notes,
		CreatedAt:        r.CreatedAt,
	}
}

func (s *Store) UpsertSnapshot(ctx context.Context, sn Snapshot) (int64, error) {
	return s.q.UpsertSnapshot(ctx, sqlcgen.UpsertSnapshotParams{
		AssetID:          sn.AssetID,
		SnapshotDate:     sn.SnapshotDate,
		BalanceCents:     sn.BalanceCents,
		ExpectedYieldPct: sn.ExpectedYieldPct,
		ActualYieldPct:   sn.ActualYieldPct,
		Notes:            sn.Notes,
	})
}

// SnapshotFilter narrows ListSnapshotsFiltered.
type SnapshotFilter struct {
	AssetID int64  // 0 = any
	Since   string // "YYYY-MM-DD" inclusive; "" = unbounded
	Until   string // "YYYY-MM-DD" inclusive; "" = unbounded
}

// ListSnapshots is the unfiltered fast path; delegates to sqlc.
func (s *Store) ListSnapshots(ctx context.Context) ([]Snapshot, error) {
	rows, err := s.q.ListSnapshots(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]Snapshot, len(rows))
	for i, r := range rows {
		out[i] = snapshotFromListRow(r)
	}
	return out, nil
}

func (s *Store) ListSnapshotsFiltered(ctx context.Context, f SnapshotFilter) ([]Snapshot, error) {
	if f.AssetID == 0 && f.Since == "" && f.Until == "" {
		return s.ListSnapshots(ctx)
	}
	where := []string{}
	args := []any{}
	if f.AssetID != 0 {
		where = append(where, "s.asset_id = ?")
		args = append(args, f.AssetID)
	}
	if f.Since != "" {
		where = append(where, "s.snapshot_date >= ?")
		args = append(args, f.Since)
	}
	if f.Until != "" {
		where = append(where, "s.snapshot_date <= ?")
		args = append(args, f.Until)
	}
	q := `SELECT s.id, s.asset_id, a.code, a.name, s.snapshot_date,
       s.balance_cents, s.expected_yield_pct, s.actual_yield_pct, s.notes, s.created_at
FROM snapshots s
JOIN assets a ON a.id = s.asset_id`
	if len(where) > 0 {
		q += " WHERE " + strings.Join(where, " AND ")
	}
	q += " ORDER BY s.snapshot_date DESC, a.code"
	rows, err := s.db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Snapshot
	for rows.Next() {
		var sn Snapshot
		if err := rows.Scan(
			&sn.ID, &sn.AssetID, &sn.AssetCode, &sn.AssetName, &sn.SnapshotDate,
			&sn.BalanceCents, &sn.ExpectedYieldPct, &sn.ActualYieldPct, &sn.Notes, &sn.CreatedAt,
		); err != nil {
			return nil, err
		}
		out = append(out, sn)
	}
	return out, rows.Err()
}

func (s *Store) GetSnapshotByID(ctx context.Context, id int64) (Snapshot, error) {
	r, err := s.q.GetSnapshotByID(ctx, id)
	if err != nil {
		return Snapshot{}, err
	}
	return snapshotFromGetRow(r), nil
}

// SnapshotPatch holds partial-update fields. snapshot_date and asset_id are
// intentionally excluded — the (asset_id, snapshot_date) pair is the natural
// key, so changing it is "delete + new POST", not a patch.
type SnapshotPatch struct {
	BalanceCents     *int64
	ExpectedYieldPct *float64
	ClearExpectedY   bool
	ActualYieldPct   *float64
	ClearActualY     bool
	Notes            *string
}

func (s *Store) PatchSnapshot(ctx context.Context, id int64, p SnapshotPatch) error {
	sets := []string{}
	args := []any{}
	if p.BalanceCents != nil {
		sets = append(sets, "balance_cents = ?")
		args = append(args, *p.BalanceCents)
	}
	if p.ClearExpectedY {
		sets = append(sets, "expected_yield_pct = NULL")
	} else if p.ExpectedYieldPct != nil {
		sets = append(sets, "expected_yield_pct = ?")
		args = append(args, *p.ExpectedYieldPct)
	}
	if p.ClearActualY {
		sets = append(sets, "actual_yield_pct = NULL")
	} else if p.ActualYieldPct != nil {
		sets = append(sets, "actual_yield_pct = ?")
		args = append(args, *p.ActualYieldPct)
	}
	if p.Notes != nil {
		sets = append(sets, "notes = ?")
		args = append(args, *p.Notes)
	}
	if len(sets) == 0 {
		if _, err := s.q.GetSnapshotByID(ctx, id); err != nil {
			return err
		}
		return nil
	}
	args = append(args, id)
	q := "UPDATE snapshots SET " + strings.Join(sets, ", ") + " WHERE id = ?"
	res, err := s.db.ExecContext(ctx, q, args...)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return sql.ErrNoRows
	}
	return nil
}

func (s *Store) DeleteSnapshot(ctx context.Context, id int64) error {
	rows, err := s.q.DeleteSnapshot(ctx, id)
	if err != nil {
		return err
	}
	if rows == 0 {
		return sql.ErrNoRows
	}
	return nil
}

// --- Transaction ---

type Transaction struct {
	ID          int64
	AssetID     int64
	AssetCode   string
	AssetName   string
	TxnDate     string
	Direction   string
	AmountCents int64
	FeeCents    int64
	Notes       string
	CreatedAt   string
}

func transactionFromListRow(r sqlcgen.ListTransactionsRow) Transaction {
	return Transaction{
		ID:          r.ID,
		AssetID:     r.AssetID,
		AssetCode:   r.AssetCode,
		AssetName:   r.AssetName,
		TxnDate:     r.TxnDate,
		Direction:   r.Direction,
		AmountCents: r.AmountCents,
		FeeCents:    r.FeeCents,
		Notes:       r.Notes,
		CreatedAt:   r.CreatedAt,
	}
}

func transactionFromGetRow(r sqlcgen.GetTransactionByIDRow) Transaction {
	return Transaction{
		ID:          r.ID,
		AssetID:     r.AssetID,
		AssetCode:   r.AssetCode,
		AssetName:   r.AssetName,
		TxnDate:     r.TxnDate,
		Direction:   r.Direction,
		AmountCents: r.AmountCents,
		FeeCents:    r.FeeCents,
		Notes:       r.Notes,
		CreatedAt:   r.CreatedAt,
	}
}

// TransactionFilter narrows ListTransactionsFiltered.
type TransactionFilter struct {
	AssetID   int64
	Direction string // "" or one of buy/sell/dividend/fee/transfer-in/transfer-out/adjust
	Since     string
	Until     string
}

func (s *Store) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := s.q.ListTransactions(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]Transaction, len(rows))
	for i, r := range rows {
		out[i] = transactionFromListRow(r)
	}
	return out, nil
}

func (s *Store) ListTransactionsFiltered(ctx context.Context, f TransactionFilter) ([]Transaction, error) {
	if f.AssetID == 0 && f.Direction == "" && f.Since == "" && f.Until == "" {
		return s.ListTransactions(ctx)
	}
	where := []string{}
	args := []any{}
	if f.AssetID != 0 {
		where = append(where, "t.asset_id = ?")
		args = append(args, f.AssetID)
	}
	if f.Direction != "" {
		where = append(where, "t.direction = ?")
		args = append(args, f.Direction)
	}
	if f.Since != "" {
		where = append(where, "t.txn_date >= ?")
		args = append(args, f.Since)
	}
	if f.Until != "" {
		where = append(where, "t.txn_date <= ?")
		args = append(args, f.Until)
	}
	q := `SELECT t.id, t.asset_id, a.code, a.name, t.txn_date,
       t.direction, t.amount_cents, t.fee_cents, t.notes, t.created_at
FROM transactions t
JOIN assets a ON a.id = t.asset_id`
	if len(where) > 0 {
		q += " WHERE " + strings.Join(where, " AND ")
	}
	q += " ORDER BY t.txn_date DESC, t.id DESC"
	rows, err := s.db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Transaction
	for rows.Next() {
		var t Transaction
		if err := rows.Scan(
			&t.ID, &t.AssetID, &t.AssetCode, &t.AssetName, &t.TxnDate,
			&t.Direction, &t.AmountCents, &t.FeeCents, &t.Notes, &t.CreatedAt,
		); err != nil {
			return nil, err
		}
		out = append(out, t)
	}
	return out, rows.Err()
}

func (s *Store) GetTransactionByID(ctx context.Context, id int64) (Transaction, error) {
	r, err := s.q.GetTransactionByID(ctx, id)
	if err != nil {
		return Transaction{}, err
	}
	return transactionFromGetRow(r), nil
}

// InsertTransaction creates a new transaction row. Transactions have no
// natural unique key (an asset can buy twice the same day with the same
// amount), so duplicate-prevention is the caller's responsibility.
func (s *Store) InsertTransaction(ctx context.Context, t Transaction) (int64, error) {
	return s.q.InsertTransaction(ctx, sqlcgen.InsertTransactionParams{
		AssetID:     t.AssetID,
		TxnDate:     t.TxnDate,
		Direction:   t.Direction,
		AmountCents: t.AmountCents,
		FeeCents:    t.FeeCents,
		Notes:       t.Notes,
	})
}

// TransactionPatch holds partial-update fields. asset_id is intentionally
// excluded — moving a txn between assets corrupts holdings history; do
// "delete + reinsert" instead.
type TransactionPatch struct {
	TxnDate     *string
	Direction   *string
	AmountCents *int64
	FeeCents    *int64
	Notes       *string
}

func (s *Store) PatchTransaction(ctx context.Context, id int64, p TransactionPatch) error {
	sets := []string{}
	args := []any{}
	if p.TxnDate != nil {
		sets = append(sets, "txn_date = ?")
		args = append(args, *p.TxnDate)
	}
	if p.Direction != nil {
		sets = append(sets, "direction = ?")
		args = append(args, *p.Direction)
	}
	if p.AmountCents != nil {
		sets = append(sets, "amount_cents = ?")
		args = append(args, *p.AmountCents)
	}
	if p.FeeCents != nil {
		sets = append(sets, "fee_cents = ?")
		args = append(args, *p.FeeCents)
	}
	if p.Notes != nil {
		sets = append(sets, "notes = ?")
		args = append(args, *p.Notes)
	}
	if len(sets) == 0 {
		if _, err := s.q.GetTransactionByID(ctx, id); err != nil {
			return err
		}
		return nil
	}
	args = append(args, id)
	q := "UPDATE transactions SET " + strings.Join(sets, ", ") + " WHERE id = ?"
	res, err := s.db.ExecContext(ctx, q, args...)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return sql.ErrNoRows
	}
	return nil
}

func (s *Store) DeleteTransaction(ctx context.Context, id int64) error {
	rows, err := s.q.DeleteTransaction(ctx, id)
	if err != nil {
		return err
	}
	if rows == 0 {
		return sql.ErrNoRows
	}
	return nil
}

// --- Holding (view) ---

type Holding struct {
	AssetID          int64
	AssetCode        string
	AssetName        string
	AssetType        string
	Bucket           string
	Channel          string
	Currency         string
	RiskLevel        sql.NullString
	AsOf             sql.NullString
	BalanceCents     sql.NullInt64
	ExpectedYieldPct sql.NullFloat64
}

// holdingFromSQLC converts pointer-typed nullables (sqlc's default for VIEWs
// since the holdings columns aren't in our column overrides) into sql.Null*
// for compatibility with csvexport (which already handles sql.Null*).
//
// Why no override: the holdings VIEW is derived from a LEFT JOIN, and sqlc
// can't introspect view-column nullability the way it can with table columns.
// Adding overrides for view columns isn't supported in sqlc.yaml's `column:`
// syntax (which expects `table.column`). Adapter is the simplest fix.
func holdingFromSQLC(h sqlcgen.Holding) Holding {
	return Holding{
		AssetID:          h.AssetID,
		AssetCode:        h.AssetCode,
		AssetName:        h.AssetName,
		AssetType:        h.AssetType,
		Bucket:           h.Bucket,
		Channel:          h.Channel,
		Currency:         h.Currency,
		RiskLevel:        nullStrFromPtr(h.RiskLevel),
		AsOf:             nullStrFromPtr(h.AsOf),
		BalanceCents:     nullInt64FromPtr(h.BalanceCents),
		ExpectedYieldPct: nullFloat64FromPtr(h.ExpectedYieldPct),
	}
}

func nullStrFromPtr(p *string) sql.NullString {
	if p == nil {
		return sql.NullString{}
	}
	return sql.NullString{String: *p, Valid: true}
}

func nullInt64FromPtr(p *int64) sql.NullInt64 {
	if p == nil {
		return sql.NullInt64{}
	}
	return sql.NullInt64{Int64: *p, Valid: true}
}

func nullFloat64FromPtr(p *float64) sql.NullFloat64 {
	if p == nil {
		return sql.NullFloat64{}
	}
	return sql.NullFloat64{Float64: *p, Valid: true}
}

func (s *Store) ListHoldings(ctx context.Context) ([]Holding, error) {
	rows, err := s.q.ListHoldings(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]Holding, len(rows))
	for i, r := range rows {
		out[i] = holdingFromSQLC(r)
	}
	return out, nil
}
